language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - git submodule update --init --recursive
  - cd application
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer update --dev
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Epsg/ --append
  - php app/console fom:user:resetroot --username root --password root --email root@root.de --silent
  - phantomjs --webdriver=9876 &
  - export PJSPID=$(echo $!)
  - sudo pip install selenium

script: phpunit -c app/ --coverage-clover ../testresults/clover.xml

after_script:
  - php bin/coveralls -v
  - cat /tmp/weblog
  - kill -9 $PJSPID
