imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     %kernel.cache_dir%/%kernel.environment%.sqlite
        memory:   true
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
